version: '3'

tasks:
  install-deps:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

  get-deps:
    cmds:
      - go get -u google.golang.org/protobuf/cmd/protoc-gen-go
      - go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc

  generate-grpc:
    cmds:
      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/api')) { New-Item -ItemType Directory -Path 'pkg/grpc/api' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/api --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/api --go-grpc_opt=paths=source_relative \
        proto/api.proto
      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/ads')) { New-Item -ItemType Directory -Path 'pkg/grpc/ads' }"
      - |
       protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/ads --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/ads --go-grpc_opt=paths=source_relative \
        proto/ads.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/campaigns')) { New-Item -ItemType Directory -Path 'pkg/grpc/campaigns' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/campaigns --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/campaigns --go-grpc_opt=paths=source_relative \
        proto/campaigns.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/advertisers')) { New-Item -ItemType Directory -Path 'pkg/grpc/advertisers' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/advertisers --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/advertisers --go-grpc_opt=paths=source_relative \
        proto/advertisers.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/time')) { New-Item -ItemType Directory -Path 'pkg/grpc/time' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/time --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/time --go-grpc_opt=paths=source_relative \
        proto/time.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/clients')) { New-Item -ItemType Directory -Path 'pkg/grpc/clients' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/clients --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/clients --go-grpc_opt=paths=source_relative \
        proto/clients.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/statistics')) { New-Item -ItemType Directory -Path 'pkg/grpc/statistics' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/statistics --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/statistics --go-grpc_opt=paths=source_relative \
        proto/statistics.proto

  generate-gateway:
    cmds:
      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/api')) { New-Item -ItemType Directory -Path 'pkg/grpc/api' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/api --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/api --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/api --grpc-gateway_opt=paths=source_relative \
        proto/api.proto
      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/ads')) { New-Item -ItemType Directory -Path 'pkg/grpc/ads' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/ads --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/ads --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/ads --grpc-gateway_opt=paths=source_relative \
        proto/ads.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/campaigns')) { New-Item -ItemType Directory -Path 'pkg/grpc/campaigns' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/campaigns --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/campaigns --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/campaigns --grpc-gateway_opt=paths=source_relative \
        proto/campaigns.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/advertisers')) { New-Item -ItemType Directory -Path 'pkg/grpc/advertisers' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/advertisers --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/advertisers --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/advertisers --grpc-gateway_opt=paths=source_relative \
        proto/advertisers.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/time')) { New-Item -ItemType Directory -Path 'pkg/grpc/time' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/time --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/time --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/time --grpc-gateway_opt=paths=source_relative \
        proto/time.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/clients')) { New-Item -ItemType Directory -Path 'pkg/grpc/clients' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/clients --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/clients --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/clients --grpc-gateway_opt=paths=source_relative \
        proto/clients.proto

      - powershell -Command "if (-Not (Test-Path -Path 'pkg/grpc/statistics')) { New-Item -ItemType Directory -Path 'pkg/grpc/statistics' }"
      - |
        protoc --proto_path=proto --proto_path=./external \
        --go_out=pkg/grpc/statistics --go_opt=paths=source_relative \
        --go-grpc_out=pkg/grpc/statistics --go-grpc_opt=paths=source_relative \
        --grpc-gateway_out=pkg/grpc/statistics --grpc-gateway_opt=paths=source_relative \
        proto/statistics.proto
