apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: "postgres:5432"
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    user: ${POSTGRES_USER}
    database: ${POSTGRES_DB}
    isDefault: true
    jsonData:
      sslmode: disable

  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100

  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090